name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0

  pdf: ^3.11.1
  printing: ^5.13.4

  bluetooth_print_plus: ^2.4.6
  esc_pos_utils_plus: ^2.0.4
  image: ^4.2.0
  shared_preferences: ^2.3.2

  url_launcher: ^6.3.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/Ice.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/Ice.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/global_ice.png
    - assets/images/app_b.jpg
    - assets/images/background_app.jpg
    - assets/images/Ice.png